n = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(n))
print('Só tem espaços?', n.isspace())
print('É um numero:',n.isnumeric())
print('É uma letra: ', n.isalpha())
print('Possue numero e letras:', n.isalnum())
print('Está em Maiuscula?', n.isupper())
print('Está em Minusculas:', n.islower())
print('Está capitalizada?', n.istitle())
